### ISSUE TITLE
Downsampled CCF error: numpy output array is read-only

### ISSUE THREAD

**Issue by berl** [AllenInstitute/ccfviewer#2]
same conda environment as #1 but with updated pyqtgraph installed via pip as per @campagnola's solution.  Now, when I click on the  100 um option in the download window and start the download I get:

```

Traceback (most recent call last):
  File "viewer.py", line 18, in <module>
    atlas_data = CCFAtlasData(resolution=resolution)
  File "C:\Users\synbio\Documents\Python_Scripts\ccfviewer\aiccf\data.py", line 45, in __init__
    resolution = self.download_and_cache()
  File "C:\Users\synbio\Documents\Python_Scripts\ccfviewer\aiccf\data.py", line 90, in download_and_cache
    self.load_image_data(image_file)
  File "C:\Users\synbio\Documents\Python_Scripts\ccfviewer\aiccf\data.py", line 111, in load_image_data
    self.image = read_nrrd_atlas(filename)
  File "C:\Users\synbio\Documents\Python_Scripts\ccfviewer\aiccf\data.py", line 151, in read_nrrd_atlas
    np.multiply(data, 255./data.max(), out=data, casting='unsafe')
ValueError: output array is read-only
```

If instead I click on the 10 um resolution and start the download, it gets up to about 33% done, hangs for a while and then exits on the same error.

**Comment by campagnola** [comment]
Fixed! I think pynrrd made a change that causes their arrays to be read-only (I bet they're using mmap).
